name: remessa_app
description: Remessa Online App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.0+33

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^4.0.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  flutter_masked_text: ^0.8.0
  flutter_statusbarcolor: ^0.2.3
  dio: ^3.0.9
  cpf_cnpj_validator: ^1.0.5
  tuple: ^1.0.3
  package_info: ^0.4.0+16
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  firebase_remote_config: ^0.4.0
  firebase_analytics: ^6.0.0
  version: ^1.0.3
  carousel_slider: ^1.4.1
  skeleton_text: ^1.0.0
  easy_i18n: ^1.0.0
  screens: ^2.3.4
  cached_network_image: ^2.2.0+1
  equatable: ^1.2.4

  # Plugins
  amplitude_flutter: ^2.2.0
  url_launcher: ^5.4.2
  onesignal_flutter: ^2.4.1
  zendesk: ^1.0.2
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.1.4+1
  share_extend: ^1.1.5
  flutter_cache_manager: ^1.2.2
  flutter_uxcam: ^1.1.1
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  build_runner: ^1.10.1
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5
  hive_generator: ^0.7.1
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1

dependency_overrides:
  analyzer: 0.39.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:  
  - resources/lang/pt.json
  - resources/lang/en.json
  - resources/images/splash_logo.png
  - images/initial_screen.png
  - images/full_icon.png
  - images/wallet.png
  - images/historic.png
  - images/send_remittance.png
  - images/transaction_details_doubts.png
  - images/step1.png
  - images/step2.png
  - images/step3.png
  - images/website_redirect.png
  - images/new_transaction_empty_state.png
  - images/simulator_empty.png
  - images/flag_brazil.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family:  RemessaIcons
      fonts:
         - asset: fonts/RemessaIcons.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
