/// Flutter icons RemessaIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RemessaIcons
///      fonts:
///       - asset: fonts/RemessaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RemessaIcons {
  RemessaIcons._();

  static const _kFontFam = 'RemessaIcons';

  static const IconData send = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData equal = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData multiply = IconData(0xe805, fontFamily: _kFontFam);
}
